language: node_js
node_js:
- node
- '4'
env:
  global:
    secure: T61aSNooK8TVL5VmPtKaNKEgvIYBZzWEBYLCOBa3A3G8bOIo7MCbX0wacMu8XdreAvG55IAxFohyeqAJ/2oe6HXyek2sruV3vzsv1FITFnJZfTYQUWyl2tezaeKwxSkNP4yhbpEMa7yrZUY4XCeMtQzu3MdHVg35TZutSwVMUs+HV1I22OPvb9V1p5KzjjYMvJIt8s4EfxtzIZoK9EdGIsFmI5WRtcY5gU79sono8+isdGyJmneNgxWZ5Virh35s4zvufE5/dGCJelwXfppPBhrOwhYFuyDvhTFRU68M8B+jpnuO+AzumBGvdho7nRgn9WmgCMWvS36rSf1ZwNZ5aoLld1NYfef2nya6PbsTPMNUQLRGUkYuk+z+PrJpnORQx3zqxJAWaSLF9uMaMabX53pVNwRlrkVUW1VL2pjgu5WbwRcVhOP3rDjml2fPXguZQNsem8Jwa12MJ24b/bi6zYw69yQ/TNZKROEDCmBIOT+yN0nBCQDOgxS9tc84UsfYUmkJ0a3I6cU7dPF0pIY0QKE5lNLXAmZF6pSprMub279T/NHX7526j1Clm6079LpLM9lsW1SBHjFa1NZBBzPOIjzV1o3AKo0UdeLs4qYqUAEXmPOn9X65+ORBzAp2EspW1hm7btEXdE+Dboa4f4mUBToFaQXDCwasMBy669g+gNo=
